/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../../index";

export interface UpdateWorkflowDto {
    nodes?: Vapi.UpdateWorkflowDtoNodesItem[];
    /** These are the options for the workflow's LLM. */
    model?: Vapi.UpdateWorkflowDtoModel;
    name?: string;
    edges?: Vapi.Edge[];
}
