/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type KnowledgeBasesDeleteResponse = Vapi.TrieveKnowledgeBase | Vapi.CustomKnowledgeBase;
