/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TestSuiteTestControllerFindAllPaginatedRequestSortOrder = "ASC" | "DESC";
export const TestSuiteTestControllerFindAllPaginatedRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
