/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type TestSuiteTestControllerFindOneResponse = Vapi.TestSuiteTestVoice | Vapi.TestSuiteTestChat;
