/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TestSuiteRunControllerFindAllPaginatedRequestSortOrder = "ASC" | "DESC";
export const TestSuiteRunControllerFindAllPaginatedRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
