/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the table you want to query.
 */
export type AnalyticsQueryTable = "call" | "subscription";
export const AnalyticsQueryTable = {
    Call: "call",
    Subscription: "subscription",
} as const;
