/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ApiRequestMethod = "POST" | "GET";
export const ApiRequestMethod = {
    Post: "POST",
    Get: "GET",
} as const;
