/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface AssistantPaginatedResponse {
    results: Vapi.Assistant[];
    metadata: Vapi.PaginationMeta;
}
