/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * These are the options for the assistant's voice.
 */
export type AssistantVoice =
    | Vapi.AzureVoice
    | Vapi.CartesiaVoice
    | Vapi.CustomVoice
    | Vapi.DeepgramVoice
    | Vapi.ElevenLabsVoice
    | Vapi.HumeVoice
    | Vapi.LmntVoice
    | Vapi.NeuphonicVoice
    | Vapi.OpenAiVoice
    | Vapi.PlayHtVoice
    | Vapi.RimeAiVoice
    | Vapi.SmallestAiVoice
    | Vapi.TavusVoice
    | Vapi.VapiVoice;
