/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the background sound in the call. Default for phone calls is 'office' and default for web calls is 'off'.
 * You can also provide a custom sound by providing a URL to an audio file.
 */
export type AssistantOverridesBackgroundSound = Vapi.AssistantOverridesBackgroundSoundZero | string;
