/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the service being used in Azure.
 */
export type AzureCredentialService = "speech" | "blob_storage";
export const AzureCredentialService = {
    Speech: "speech",
    BlobStorage: "blob_storage",
} as const;
