/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the level of the log message.
 */
export type CallLogPrivilegedLevel = "INFO" | "LOG" | "WARN" | "ERROR" | "CHECKPOINT";
export const CallLogPrivilegedLevel = {
    Info: "INFO",
    Log: "LOG",
    Warn: "WARN",
    Error: "ERROR",
    Checkpoint: "CHECKPOINT",
} as const;
