/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CartesiaExperimentalControlsEmotion =
    | "anger:lowest"
    | "anger:low"
    | "anger:high"
    | "anger:highest"
    | "positivity:lowest"
    | "positivity:low"
    | "positivity:high"
    | "positivity:highest"
    | "surprise:lowest"
    | "surprise:low"
    | "surprise:high"
    | "surprise:highest"
    | "sadness:lowest"
    | "sadness:low"
    | "sadness:high"
    | "sadness:highest"
    | "curiosity:lowest"
    | "curiosity:low"
    | "curiosity:high"
    | "curiosity:highest";
export const CartesiaExperimentalControlsEmotion = {
    AngerLowest: "anger:lowest",
    AngerLow: "anger:low",
    AngerHigh: "anger:high",
    AngerHighest: "anger:highest",
    PositivityLowest: "positivity:lowest",
    PositivityLow: "positivity:low",
    PositivityHigh: "positivity:high",
    PositivityHighest: "positivity:highest",
    SurpriseLowest: "surprise:lowest",
    SurpriseLow: "surprise:low",
    SurpriseHigh: "surprise:high",
    SurpriseHighest: "surprise:highest",
    SadnessLowest: "sadness:lowest",
    SadnessLow: "sadness:low",
    SadnessHigh: "sadness:high",
    SadnessHighest: "sadness:highest",
    CuriosityLowest: "curiosity:lowest",
    CuriosityLow: "curiosity:low",
    CuriosityHigh: "curiosity:high",
    CuriosityHighest: "curiosity:highest",
} as const;
