/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the language that will be used. This is optional and will default to the correct language for the voiceId.
 */
export type CartesiaVoiceLanguage =
    | "en"
    | "de"
    | "es"
    | "fr"
    | "ja"
    | "pt"
    | "zh"
    | "hi"
    | "it"
    | "ko"
    | "nl"
    | "pl"
    | "ru"
    | "sv"
    | "tr";
export const CartesiaVoiceLanguage = {
    En: "en",
    De: "de",
    Es: "es",
    Fr: "fr",
    Ja: "ja",
    Pt: "pt",
    Zh: "zh",
    Hi: "hi",
    It: "it",
    Ko: "ko",
    Nl: "nl",
    Pl: "pl",
    Ru: "ru",
    Sv: "sv",
    Tr: "tr",
} as const;
