/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the model that will be used. This is optional and will default to the correct model for the voiceId.
 */
export type CartesiaVoiceModel = "sonic-2" | "sonic-english" | "sonic-multilingual" | "sonic-preview" | "sonic";
export const CartesiaVoiceModel = {
    Sonic2: "sonic-2",
    SonicEnglish: "sonic-english",
    SonicMultilingual: "sonic-multilingual",
    SonicPreview: "sonic-preview",
    Sonic: "sonic",
} as const;
