/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface CartesiaExperimentalControls {
    speed?: Vapi.CartesiaExperimentalControlsSpeed;
    emotion?: Vapi.CartesiaExperimentalControlsEmotion;
}
