/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChatCompletionMessageMetadata {
    taskName: string;
    taskType: string;
    taskOutput: string;
    taskState?: Record<string, unknown>;
    nodeTrace?: string[];
}
