/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ChatCompletionsDto {
    messages: Vapi.ChatCompletionMessageWorkflows[];
    workflowId?: string;
    workflow?: Vapi.CreateWorkflowDto;
}
