/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ChatCompletionMessageWorkflows {
    role: Record<string, unknown>;
    content?: string;
    metadata?: Vapi.ChatCompletionMessageMetadata;
}
