/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ClientInboundMessageTransfer {
    /** This is the type of the message. Send "transfer" message to transfer the call to a destination. */
    type: "transfer";
    /** This is the destination to transfer the call to. */
    destination?: Vapi.ClientInboundMessageTransferDestination;
    /** This is the content to say. */
    content?: string;
}
