/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the destination to transfer the call to.
 */
export type ClientInboundMessageTransferDestination = Vapi.TransferDestinationNumber | Vapi.TransferDestinationSip;
