/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientMessageLanguageChangeDetected {
    /** This is the type of the message. "language-change-detected" is sent when the transcriber is automatically switched based on the detected language. */
    type: "language-change-detected";
    /** This is the language the transcriber is switched to. */
    language: string;
}
