/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ClientMessageTransferUpdate {
    /** This is the type of the message. "transfer-update" is sent whenever a transfer happens. */
    type: "transfer-update";
    /** This is the destination of the transfer. */
    destination?: Vapi.ClientMessageTransferUpdateDestination;
    /** This is the assistant that the call is being transferred to. This is only sent if `destination.type` is "assistant". */
    toAssistant?: Vapi.CreateAssistantDto;
    /** This is the assistant that the call is being transferred from. This is only sent if `destination.type` is "assistant". */
    fromAssistant?: Vapi.CreateAssistantDto;
    /** This is the step that the conversation moved to. */
    toStepRecord?: Record<string, unknown>;
    /** This is the step that the conversation moved from. = */
    fromStepRecord?: Record<string, unknown>;
}
