/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateAssistantDtoBackgroundSoundZero = "off" | "office";
export const CreateAssistantDtoBackgroundSoundZero = {
    Off: "off",
    Office: "office",
} as const;
