/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface CreateWorkflowDto {
    nodes: Vapi.CreateWorkflowDtoNodesItem[];
    /** These are the options for the workflow's LLM. */
    model?: Vapi.CreateWorkflowDtoModel;
    name: string;
    edges: Vapi.Edge[];
}
