/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateTwilioCredentialDto {
    provider: "twilio";
    /** This is not returned in the API. */
    authToken: string;
    accountSid: string;
    /** This is the name of credential. This is just for your reference. */
    name?: string;
}
