/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CredentialWebhookDtoOperation = "creation" | "override" | "refresh";
export const CredentialWebhookDtoOperation = {
    Creation: "creation",
    Override: "override",
    Refresh: "refresh",
} as const;
