/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CredentialWebhookDtoType = "auth" | "sync" | "forward";
export const CredentialWebhookDtoType = {
    Auth: "auth",
    Sync: "sync",
    Forward: "forward",
} as const;
