/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface CredentialSessionDto {
    /** The type of credential to generate a session for. Only Nango user-facing providers are supported. */
    provider: Vapi.CredentialSessionDtoProvider;
}
