/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface CredentialWebhookDto {
    type: Vapi.CredentialWebhookDtoType;
    operation: Vapi.CredentialWebhookDtoOperation;
    from: string;
    connectionId: string;
    authMode: Vapi.CredentialWebhookDtoAuthMode;
    providerConfigKey: string;
    provider: string;
    environment: string;
    success: boolean;
    endUser: Vapi.CredentialEndUser;
    error?: Vapi.CredentialSessionError;
}
