/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CredentialWebhookDtoAuthMode = "OAUTH2" | "API_KEY" | "BASIC";
export const CredentialWebhookDtoAuthMode = {
    Oauth2: "OAUTH2",
    ApiKey: "API_KEY",
    Basic: "BASIC",
} as const;
