/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of credential to generate a session for. Only Nango user-facing providers are supported.
 */
export type CredentialSessionDtoProvider =
    | "google.calendar.oauth2-client"
    | "google.calendar.oauth2-authorization"
    | "google.sheets.oauth2-authorization"
    | "slack.oauth2-authorization";
export const CredentialSessionDtoProvider = {
    GoogleCalendarOauth2Client: "google.calendar.oauth2-client",
    GoogleCalendarOauth2Authorization: "google.calendar.oauth2-authorization",
    GoogleSheetsOauth2Authorization: "google.sheets.oauth2-authorization",
    SlackOauth2Authorization: "slack.oauth2-authorization",
} as const;
