/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ElevenLabsTranscriber {
    /** This is the transcription provider that will be used. */
    provider: "11labs";
    /** This is the model that will be used for the transcription. */
    model?: "scribe_v1";
    language?: Vapi.ElevenLabsTranscriberLanguage;
    /** This is the plan for voice provider fallbacks in the event that the primary voice provider fails. */
    fallbackPlan?: Vapi.FallbackTranscriberPlan;
}
