/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the model that will be used. Defaults to 'v1' when not specified.
 */
export type FallbackRimeAiVoiceModel = "v1" | "mist" | "mistv2";
export const FallbackRimeAiVoiceModel = {
    V1: "v1",
    Mist: "mist",
    Mistv2: "mistv2",
} as const;
