/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the model that will be used. Defaults to 'neu_fast' if not specified.
 */
export type FallbackNeuphonicVoiceModel = "neu_hq" | "neu_fast";
export const FallbackNeuphonicVoiceModel = {
    NeuHq: "neu_hq",
    NeuFast: "neu_fast",
} as const;
