/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type FallbackPlanVoicesItem =
    | Vapi.FallbackAzureVoice
    | Vapi.FallbackCartesiaVoice
    | Vapi.FallbackHumeVoice
    | Vapi.FallbackCustomVoice
    | Vapi.FallbackDeepgramVoice
    | Vapi.FallbackElevenLabsVoice
    | Vapi.FallbackVapiVoice
    | Vapi.FallbackLmntVoice
    | Vapi.FallbackOpenAiVoice
    | Vapi.FallbackPlayHtVoice
    | Vapi.FallbackRimeAiVoice
    | Vapi.FallbackSmallestAiVoice
    | Vapi.FallbackTavusVoice;
