/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface FallbackSpeechmaticsTranscriber {
    /** This is the transcription provider that will be used. */
    provider: "speechmatics";
    /** This is the model that will be used for the transcription. */
    model?: "default";
    language?: Vapi.FallbackSpeechmaticsTranscriberLanguage;
}
