/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FallbackSmallestAiVoiceIdEnum =
    | "emily"
    | "jasmine"
    | "arman"
    | "james"
    | "mithali"
    | "aravind"
    | "raj"
    | "diya"
    | "raman"
    | "ananya"
    | "isha"
    | "william"
    | "aarav"
    | "monika"
    | "niharika"
    | "deepika"
    | "raghav"
    | "kajal"
    | "radhika"
    | "mansi"
    | "nisha"
    | "saurabh"
    | "pooja"
    | "saina"
    | "sanya";
export const FallbackSmallestAiVoiceIdEnum = {
    Emily: "emily",
    Jasmine: "jasmine",
    Arman: "arman",
    James: "james",
    Mithali: "mithali",
    Aravind: "aravind",
    Raj: "raj",
    Diya: "diya",
    Raman: "raman",
    Ananya: "ananya",
    Isha: "isha",
    William: "william",
    Aarav: "aarav",
    Monika: "monika",
    Niharika: "niharika",
    Deepika: "deepika",
    Raghav: "raghav",
    Kajal: "kajal",
    Radhika: "radhika",
    Mansi: "mansi",
    Nisha: "nisha",
    Saurabh: "saurabh",
    Pooja: "pooja",
    Saina: "saina",
    Sanya: "sanya",
} as const;
