/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type FallbackTranscriberPlanTranscribersItem =
    | Vapi.FallbackAssemblyAiTranscriber
    | Vapi.FallbackAzureSpeechTranscriber
    | Vapi.FallbackCustomTranscriber
    | Vapi.FallbackDeepgramTranscriber
    | Vapi.FallbackElevenLabsTranscriber
    | Vapi.FallbackGladiaTranscriber
    | Vapi.FallbackGoogleTranscriber
    | Vapi.FallbackTalkscriberTranscriber
    | Vapi.FallbackSpeechmaticsTranscriber
    | Vapi.FallbackOpenAiTranscriber;
