/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FallbackLmntVoiceIdEnum = "lily" | "daniel";
export const FallbackLmntVoiceIdEnum = {
    Lily: "lily",
    Daniel: "daniel",
} as const;
