/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the language code (ISO 639-1) that will be used.
 *
 * @default 'en-US'
 */
export type FallbackVapiVoiceLanguage =
    | "en-US"
    | "en-GB"
    | "en-AU"
    | "en-CA"
    | "ja"
    | "zh"
    | "de"
    | "hi"
    | "fr-FR"
    | "fr-CA"
    | "ko"
    | "pt-BR"
    | "pt-PT"
    | "it"
    | "es-ES"
    | "es-MX"
    | "id"
    | "nl"
    | "tr"
    | "fil"
    | "pl"
    | "sv"
    | "bg"
    | "ro"
    | "ar-SA"
    | "ar-AE"
    | "cs"
    | "el"
    | "fi"
    | "hr"
    | "ms"
    | "sk"
    | "da"
    | "ta"
    | "uk"
    | "ru"
    | "hu"
    | "no"
    | "vi";
export const FallbackVapiVoiceLanguage = {
    EnUs: "en-US",
    EnGb: "en-GB",
    EnAu: "en-AU",
    EnCa: "en-CA",
    Ja: "ja",
    Zh: "zh",
    De: "de",
    Hi: "hi",
    FrFr: "fr-FR",
    FrCa: "fr-CA",
    Ko: "ko",
    PtBr: "pt-BR",
    PtPt: "pt-PT",
    It: "it",
    EsEs: "es-ES",
    EsMx: "es-MX",
    Id: "id",
    Nl: "nl",
    Tr: "tr",
    Fil: "fil",
    Pl: "pl",
    Sv: "sv",
    Bg: "bg",
    Ro: "ro",
    ArSa: "ar-SA",
    ArAe: "ar-AE",
    Cs: "cs",
    El: "el",
    Fi: "fi",
    Hr: "hr",
    Ms: "ms",
    Sk: "sk",
    Da: "da",
    Ta: "ta",
    Uk: "uk",
    Ru: "ru",
    Hu: "hu",
    No: "no",
    Vi: "vi",
} as const;
