/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FallbackGladiaTranscriberLanguageBehaviour =
    | "manual"
    | "automatic single language"
    | "automatic multiple languages";
export const FallbackGladiaTranscriberLanguageBehaviour = {
    Manual: "manual",
    AutomaticSingleLanguage: "automatic single language",
    AutomaticMultipleLanguages: "automatic multiple languages",
} as const;
