/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface FallbackAzureVoice {
    /** This is the voice provider that will be used. */
    provider: "azure";
    /** This is the provider-specific ID that will be used. */
    voiceId: Vapi.FallbackAzureVoiceId;
    /** This is the speed multiplier that will be used. */
    speed?: number;
    /** This is the plan for chunking the model output before it is sent to the voice provider. */
    chunkPlan?: Vapi.ChunkPlan;
    oneOf?: unknown;
}
