/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the language that will be set for the transcription.
 */
export type FallbackGoogleTranscriberLanguage =
    | "Multilingual"
    | "Arabic"
    | "Bengali"
    | "Bulgarian"
    | "Chinese"
    | "Croatian"
    | "Czech"
    | "Danish"
    | "Dutch"
    | "English"
    | "Estonian"
    | "Finnish"
    | "French"
    | "German"
    | "Greek"
    | "Hebrew"
    | "Hindi"
    | "Hungarian"
    | "Indonesian"
    | "Italian"
    | "Japanese"
    | "Korean"
    | "Latvian"
    | "Lithuanian"
    | "Norwegian"
    | "Polish"
    | "Portuguese"
    | "Romanian"
    | "Russian"
    | "Serbian"
    | "Slovak"
    | "Slovenian"
    | "Spanish"
    | "Swahili"
    | "Swedish"
    | "Thai"
    | "Turkish"
    | "Ukrainian"
    | "Vietnamese";
export const FallbackGoogleTranscriberLanguage = {
    Multilingual: "Multilingual",
    Arabic: "Arabic",
    Bengali: "Bengali",
    Bulgarian: "Bulgarian",
    Chinese: "Chinese",
    Croatian: "Croatian",
    Czech: "Czech",
    Danish: "Danish",
    Dutch: "Dutch",
    English: "English",
    Estonian: "Estonian",
    Finnish: "Finnish",
    French: "French",
    German: "German",
    Greek: "Greek",
    Hebrew: "Hebrew",
    Hindi: "Hindi",
    Hungarian: "Hungarian",
    Indonesian: "Indonesian",
    Italian: "Italian",
    Japanese: "Japanese",
    Korean: "Korean",
    Latvian: "Latvian",
    Lithuanian: "Lithuanian",
    Norwegian: "Norwegian",
    Polish: "Polish",
    Portuguese: "Portuguese",
    Romanian: "Romanian",
    Russian: "Russian",
    Serbian: "Serbian",
    Slovak: "Slovak",
    Slovenian: "Slovenian",
    Spanish: "Spanish",
    Swahili: "Swahili",
    Swedish: "Swedish",
    Thai: "Thai",
    Turkish: "Turkish",
    Ukrainian: "Ukrainian",
    Vietnamese: "Vietnamese",
} as const;
