/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the provider-specific ID that will be used.
 */
export type FallbackTavusVoiceVoiceId = "r52da2535a" | string;
