/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface FallbackGoogleTranscriber {
    /** This is the transcription provider that will be used. */
    provider: "google";
    /** This is the model that will be used for the transcription. */
    model?: Vapi.FallbackGoogleTranscriberModel;
    /** This is the language that will be set for the transcription. */
    language?: Vapi.FallbackGoogleTranscriberLanguage;
}
