/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface FallbackElevenLabsTranscriber {
    /** This is the transcription provider that will be used. */
    provider: "11labs";
    /** This is the model that will be used for the transcription. */
    model?: "scribe_v1";
    language?: Vapi.FallbackElevenLabsTranscriberLanguage;
}
