/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FallbackGladiaTranscriberModel = "fast" | "accurate";
export const FallbackGladiaTranscriberModel = {
    Fast: "fast",
    Accurate: "accurate",
} as const;
