/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FallbackAzureVoiceVoiceId = "andrew" | "brian" | "emma";
export const FallbackAzureVoiceVoiceId = {
    Andrew: "andrew",
    Brian: "brian",
    Emma: "emma",
} as const;
