/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the model that will be used for the transcription.
 */
export type FallbackOpenAiTranscriberModel = "gpt-4o-transcribe" | "gpt-4o-mini-transcribe";
export const FallbackOpenAiTranscriberModel = {
    Gpt4OTranscribe: "gpt-4o-transcribe",
    Gpt4OMiniTranscribe: "gpt-4o-mini-transcribe",
} as const;
