/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FileStatus = "processing" | "done" | "failed";
export const FileStatus = {
    Processing: "processing",
    Done: "done",
    Failed: "failed",
} as const;
