/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FormatPlanFormattersEnabledItem =
    | "markdown"
    | "asterisk"
    | "quote"
    | "dash"
    | "newline"
    | "colon"
    | "acronym"
    | "dollarAmount"
    | "email"
    | "date"
    | "time"
    | "distance"
    | "unit"
    | "percentage"
    | "phoneNumber"
    | "number";
export const FormatPlanFormattersEnabledItem = {
    Markdown: "markdown",
    Asterisk: "asterisk",
    Quote: "quote",
    Dash: "dash",
    Newline: "newline",
    Colon: "colon",
    Acronym: "acronym",
    DollarAmount: "dollarAmount",
    Email: "email",
    Date: "date",
    Time: "time",
    Distance: "distance",
    Unit: "unit",
    Percentage: "percentage",
    PhoneNumber: "phoneNumber",
    Number: "number",
} as const;
