/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface Gather {
    type: "gather";
    output: Vapi.JsonSchema;
    /** This is whether or not the workflow should read back the gathered data to the user, and ask about its correctness. */
    confirmContent?: boolean;
    /**
     * This is a list of hooks for a task.
     * Each hook is a list of tasks to run on a trigger (such as on start, on failure, etc).
     * Only Say is supported for now.
     */
    hooks?: Vapi.Hook[];
    /** This is the number of times we should try to gather the information from the user before we failover to the fail path. An example of this would be a user refusing to give their phone number for privacy reasons, and then going down a different path on account of this */
    maxRetries?: number;
    /** This is a liquid templating string. On the first call to Gather, the template will be filled out with variables from the context, and will be spoken verbatim to the user. An example would be "Base on your zipcode, it looks like you could be in one of these counties: {{ counties | join: ", " }}. Which one do you live in?" */
    literalTemplate?: string;
    name: string;
    /** This is for metadata you want to store on the task. */
    metadata?: Record<string, unknown>;
}
