/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type HookOn = "task.start" | "task.output.confirmation" | "task.delayed";
export const HookOn = {
    TaskStart: "task.start",
    TaskOutputConfirmation: "task.output.confirmation",
    TaskDelayed: "task.delayed",
} as const;
