/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface KeypadInputPlan {
    /**
     * This keeps track of whether the user has enabled keypad input.
     * By default, it is off.
     *
     * @default false
     */
    enabled?: boolean;
    /**
     * This is the time in seconds to wait before processing the input.
     * If the input is not received within this time, the input will be ignored.
     * If set to "off", the input will be processed when the user enters a delimiter or immediately if no delimiter is used.
     *
     * @default 2
     */
    timeoutSeconds?: number;
    /**
     * This is the delimiter(s) that will be used to process the input.
     * Can be '#', '*', or an empty array.
     */
    delimiters?: Vapi.KeypadInputPlanDelimiters;
}
