/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface KnowledgeBase {
    /** The name of the knowledge base */
    name: string;
    /** The provider of the knowledge base */
    provider: "google";
    /** The model to use for the knowledge base */
    model?: Vapi.KnowledgeBaseModel;
    /** A description of the knowledge base */
    description: string;
    /** The file IDs associated with this knowledge base */
    fileIds: string[];
}
