/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the provider for the smart endpointing plan.
 */
export type LivekitSmartEndpointingPlanProvider = "vapi" | "livekit";
export const LivekitSmartEndpointingPlanProvider = {
    Vapi: "vapi",
    Livekit: "livekit",
} as const;
