/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the model that will be used for text-to-speech.
 */
export type OpenAiVoiceModel = "tts-1" | "tts-1-hd" | "gpt-4o-mini-tts";
export const OpenAiVoiceModel = {
    Tts1: "tts-1",
    Tts1Hd: "tts-1-hd",
    Gpt4OMiniTts: "gpt-4o-mini-tts",
} as const;
