/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OpenAiVoicemailDetectionPlan {
    /** This is the provider to use for voicemail detection. */
    provider: "openai";
    /**
     * This is how long should we listen in order to determine if we were sent to voicemail or not?
     *
     * @default 15
     */
    voicemailExpectedDurationSeconds: number;
}
