/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the provider-specific ID that will be used.
 * Please note that ash, ballad, coral, sage, and verse may only be used with realtime models.
 */
export type OpenAiVoiceId = Vapi.OpenAiVoiceIdEnum | string;
