/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OpenAiVoiceIdEnum = "alloy" | "echo" | "fable" | "onyx" | "nova" | "shimmer";
export const OpenAiVoiceIdEnum = {
    Alloy: "alloy",
    Echo: "echo",
    Fable: "fable",
    Onyx: "onyx",
    Nova: "nova",
    Shimmer: "shimmer",
} as const;
