/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Say {
    type: "say";
    exact?: string;
    prompt?: string;
    name: string;
    /** This is for metadata you want to store on the task. */
    metadata?: Record<string, unknown>;
}
