/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the status of the call.
 */
export type ServerMessageStatusUpdateStatus =
    | "scheduled"
    | "queued"
    | "ringing"
    | "in-progress"
    | "forwarding"
    | "ended";
export const ServerMessageStatusUpdateStatus = {
    Scheduled: "scheduled",
    Queued: "queued",
    Ringing: "ringing",
    InProgress: "in-progress",
    Forwarding: "forwarding",
    Ended: "ended",
} as const;
