/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type StartSpeakingPlanCustomEndpointingRulesItem =
    | Vapi.AssistantCustomEndpointingRule
    | Vapi.CustomerCustomEndpointingRule
    | Vapi.BothCustomEndpointingRule;
