/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the status of the subscription. Past due subscriptions are subscriptions
 * with past due payments.
 */
export type SubscriptionStatus = "active" | "frozen";
export const SubscriptionStatus = {
    Active: "active",
    Frozen: "frozen",
} as const;
