/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface TargetPlan {
    /** This is the phoneNumberId that is being tested. */
    phoneNumberId?: string;
    /** This is the phone number that is being tested. Only use this if you have not imported the phone number to Vapi. */
    phoneNumber?: Vapi.TestSuitePhoneNumber;
    /** This is the assistantId that is being tested. */
    assistantId?: string;
}
