/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface TestSuiteRunTestResult {
    /** This is the test that was run. */
    test: Vapi.TestSuiteTestVoice;
    /** These are the attempts made for this test. */
    attempts: Vapi.TestSuiteRunTestAttempt[];
}
