/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface TestSuitesPaginatedResponse {
    results: Vapi.TestSuite[];
    metadata: Vapi.PaginationMeta;
}
