/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface TestSuiteTestsPaginatedResponse {
    /** A list of test suite tests. */
    results: Vapi.TestSuiteTestsPaginatedResponseResultsItem[];
    /** Metadata about the pagination. */
    metadata: Vapi.PaginationMeta;
}
