/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface TestSuiteRunTestAttemptCall {
    /** This is the artifact of the call. */
    artifact: Vapi.Artifact;
}
