/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the current status of the test suite run.
 */
export type TestSuiteRunStatus = "queued" | "in-progress" | "completed" | "failed";
export const TestSuiteRunStatus = {
    Queued: "queued",
    InProgress: "in-progress",
    Completed: "completed",
    Failed: "failed",
} as const;
