/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the result of the test suite.
 */
export type TestSuiteRunScorerAiResult = "pass" | "fail";
export const TestSuiteRunScorerAiResult = {
    Pass: "pass",
    Fail: "fail",
} as const;
