/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface TextContent {
    type: "text";
    text: string;
    language: Vapi.TextContentLanguage;
}
