/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface TransferAssistantHookAction {
    /** This is the type of action - must be "transfer" */
    type: "transfer";
    /** This is the destination details for the transfer - can be a phone number or SIP URI */
    destination?: Vapi.TransferAssistantHookActionDestination;
}
