/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransportCostProvider = "twilio" | "vonage" | "vapi";
export const TransportCostProvider = {
    Twilio: "twilio",
    Vonage: "vonage",
    Vapi: "vapi",
} as const;
