/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the destination details for the transfer - can be a phone number or SIP URI
 */
export type TransferAssistantHookActionDestination = Vapi.TransferDestinationNumber | Vapi.TransferDestinationSip;
