/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Transfer {
    type: "transfer";
    destination: Record<string, unknown>;
    name: string;
    /** This is for metadata you want to store on the task. */
    metadata?: Record<string, unknown>;
}
