/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TwilioVoicemailDetectionPlanVoicemailDetectionTypesItem =
    | "machine_start"
    | "human"
    | "fax"
    | "unknown"
    | "machine_end_beep"
    | "machine_end_silence"
    | "machine_end_other";
export const TwilioVoicemailDetectionPlanVoicemailDetectionTypesItem = {
    MachineStart: "machine_start",
    Human: "human",
    Fax: "fax",
    Unknown: "unknown",
    MachineEndBeep: "machine_end_beep",
    MachineEndSilence: "machine_end_silence",
    MachineEndOther: "machine_end_other",
} as const;
