/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface UpdateSupabaseCredentialDto {
    /** This is the name of credential. This is just for your reference. */
    name?: string;
    bucketPlan?: Vapi.SupabaseBucketPlan;
}
