/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface UpdateWebhookCredentialDto {
    /** This is the authentication plan. Currently supports OAuth2 RFC 6749. */
    authenticationPlan?: Vapi.OAuth2AuthenticationPlan;
    /** This is the name of credential. This is just for your reference. */
    name?: string;
}
