/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The voices provided by Vapi
 */
export type VapiVoiceVoiceId =
    | "Elliot"
    | "Rohan"
    | "Lily"
    | "Savannah"
    | "Hana"
    | "Neha"
    | "Cole"
    | "Harry"
    | "Paige"
    | "Spencer";
export const VapiVoiceVoiceId = {
    Elliot: "Elliot",
    Rohan: "Rohan",
    Lily: "Lily",
    Savannah: "Savannah",
    Hana: "Hana",
    Neha: "Neha",
    Cole: "Cole",
    Harry: "Harry",
    Paige: "Paige",
    Spencer: "Spencer",
} as const;
