/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface VapiSmartEndpointingPlan {
    /** This is the provider for the smart endpointing plan. */
    provider: Vapi.VapiSmartEndpointingPlanProvider;
}
