/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the sub type of the cost.
 */
export type VapiCostSubType = "normal" | "overage";
export const VapiCostSubType = {
    Normal: "normal",
    Overage: "overage",
} as const;
