/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type UpdateWorkflowDtoNodesItem = Vapi.Say | Vapi.Gather | Vapi.ApiRequest | Vapi.Hangup | Vapi.Transfer;
