/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type PhoneNumbersCreateRequest =
    | Vapi.CreateByoPhoneNumberDto
    | Vapi.CreateTwilioPhoneNumberDto
    | Vapi.CreateVonagePhoneNumberDto
    | Vapi.CreateVapiPhoneNumberDto
    | Vapi.CreateTelnyxPhoneNumberDto;
