/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type PhoneNumbersUpdateRequest =
    | Vapi.UpdateByoPhoneNumberDto
    | Vapi.UpdateTwilioPhoneNumberDto
    | Vapi.UpdateVonagePhoneNumberDto
    | Vapi.UpdateVapiPhoneNumberDto
    | Vapi.UpdateTelnyxPhoneNumberDto;
