/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type PhoneNumbersUpdateResponse =
    | Vapi.ByoPhoneNumber
    | Vapi.TwilioPhoneNumber
    | Vapi.VonagePhoneNumber
    | Vapi.VapiPhoneNumber
    | Vapi.TelnyxPhoneNumber;
