/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateAssistantDtoBackgroundSoundZero = "off" | "office";
export const UpdateAssistantDtoBackgroundSoundZero = {
    Off: "off",
    Office: "office",
} as const;
