/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

/**
 * These are the options for the assistant's LLM.
 */
export type UpdateAssistantDtoModel =
    | Vapi.AnyscaleModel
    | Vapi.AnthropicModel
    | Vapi.CerebrasModel
    | Vapi.CustomLlmModel
    | Vapi.DeepInfraModel
    | Vapi.DeepSeekModel
    | Vapi.GoogleModel
    | Vapi.GroqModel
    | Vapi.InflectionAiModel
    | Vapi.OpenAiModel
    | Vapi.OpenRouterModel
    | Vapi.PerplexityAiModel
    | Vapi.TogetherAiModel
    | Vapi.VapiModel
    | Vapi.XaiModel;
