/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LogsGetRequestSortOrder = "ASC" | "DESC";
export const LogsGetRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
