/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LogsGetRequestType = "API" | "Webhook" | "Call" | "Provider";
export const LogsGetRequestType = {
    Api: "API",
    Webhook: "Webhook",
    Call: "Call",
    Provider: "Provider",
} as const;
