/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type ToolsUpdateRequest =
    | Vapi.UpdateDtmfToolDto
    | Vapi.UpdateEndCallToolDto
    | Vapi.UpdateFunctionToolDto
    | Vapi.UpdateGhlToolDto
    | Vapi.UpdateMakeToolDto
    | Vapi.UpdateTransferCallToolDto
    | Vapi.UpdateOutputToolDto
    | Vapi.UpdateBashToolDto
    | Vapi.UpdateComputerToolDto
    | Vapi.UpdateTextEditorToolDto
    | Vapi.UpdateQueryToolDto
    | Vapi.UpdateGoogleCalendarCreateEventToolDto
    | Vapi.UpdateGoogleSheetsRowAppendToolDto
    | Vapi.UpdateGoogleCalendarCheckAvailabilityToolDto
    | Vapi.UpdateSlackSendMessageToolDto
    | Vapi.UpdateSmsSendToolDto
    | Vapi.UpdateMcpToolDto;
