/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type ToolsCreateRequest =
    | Vapi.CreateDtmfToolDto
    | Vapi.CreateEndCallToolDto
    | Vapi.CreateFunctionToolDto
    | Vapi.CreateGhlToolDto
    | Vapi.CreateMakeToolDto
    | Vapi.CreateTransferCallToolDto
    | Vapi.CreateOutputToolDto
    | Vapi.CreateBashToolDto
    | Vapi.CreateComputerToolDto
    | Vapi.CreateTextEditorToolDto
    | Vapi.CreateQueryToolDto
    | Vapi.CreateGoogleCalendarCreateEventToolDto
    | Vapi.CreateGoogleSheetsRowAppendToolDto
    | Vapi.CreateGoogleCalendarCheckAvailabilityToolDto
    | Vapi.CreateSlackSendMessageToolDto
    | Vapi.CreateSmsSendToolDto
    | Vapi.CreateMcpToolDto;
